frida-gum-sys/build.rs
This fixes an issue when targeting Android.
Note that the target_os check is insufficient, as it runs at BUILD time, not at RUN time...
Please merge and cut a release.
=> android_buildfix: don't link pthread when building for android

frida-gum/src/instruction_writer.rs
This adds a few more methods to the instruction writer, and fixes a couple of typos.
Also makes registers comparable and copyable.
=> Add some methods to the Aarch64 instruction writer

frida-gum/src/instruction_writer.rs
Adds `reset` and `put_branch_address` methods to `InstructionWriter`, with implementations for x86_64 and aarch64.
=> Add reset and put_branch_address methods to InstructionWriter

frida-gum/src/cpu_context.rs, frida-gum/src/interceptor/invocation_listener.rs
This PR adds retrieval of the `CpuContext` to `InvocationContext`, and also adds accessors for the general purpose registers on aarch64.
=> Add cpu_context to InvocationContext

frida-gum/src/instruction_writer.rs
Also add `Drop` implementations so that if you created an `InstructionWriter` with `::new`, the writer is unref-ed correctly.
=> Add `flush` and `new` methods to the `InstructionWriter` trait

frida-gum/src/module.rs
The `Module` struct only exposes `find_export_by_name`. Gum also provides `find_symbol_by_name`, expose that too to resolve non-exported symbols.
=> Add Module::find_symbol_by_name

frida-gum/src/interceptor/invocation_listener.rs
Fixed invocation_listener_transform to use the supplied argument (invocation_listener) instead of allocating a mutable reference on the stack.
=> Fixed invocation_listener_transform to properly reference user_data

frida-gum/src/module.rs
Gum's `gum_module_find_symbol_by_name()`, unlike
`gum_module_find_export_by_name()`, requires its `module_name` argument to
be non-NULL.
I overlooked this when I submitted my previous PR (#31) to expose `Module::find_symbol_by_name`.
This PR fixes that.
=> Fix Module::find_symbol_by_name to require a module name

frida-gum/src/cpu_context.rs
The `backtracer` module can generate backtraces on its own, or from a provided `GumCpuContext` (using `accurate_with_context`, `fuzzy_with_context`).
However, there doesn't seem to be an easy way to get one such `gum_sys::GumCpuContext` from a `gum::CpuContext`: there's one inside, but it's not exposed.
So this PR adds the `CpuContext::backtrace_accurate` and `CpuContext::backtrace_fuzzy` methods to generate backtraces using the `CpuContext`'s internal `GumCpuContext`.
=> Add methods to generate backtraces from a CpuContext

frida-gum/Cargo.toml
This PR bumps capstone version
capstone: 0.10.0 -> 0.11.0
capstone-sys: 0.14.0 -> 0.15.0
=> Bump capstone, capstone-sys version

Cargo.toml, examples/gum/debug_symbol/Cargo.toml, examples/gum/debug_symbol/src/main.rs, frida-gum/src/debug_symbol.rs, frida-gum/src/lib.rs
Added support for calling Frida's `gum_symbol_details_from_address` function by creating a new module `symbol_util`.
The intention is for `symbol_util.rs` to mirror `gum/gumsymbolutil.h`.
There's a new struct `DebugSymbolDetails` to wrap Frida's `GumDebugSymbolDetails`, along with relevant methods for extracting its fields (`address`, `module_name`, `symbol_name`, `file_name`, `line_number`).
=> Added module debug_symbol

frida-gum-sys/src/lib.rs
After the update to frida 16, excluding that line on linux+arm64 is not necessary anymore, and in fact after updating to frida 16 `frida-gum` cannot build on linux+arm64 anymore.
This works:
```
frida-gum = { git = "https://github.com/frida/frida-rust", rev = "0226bf9ca8171cba864024dfd21364e7b1833392", features = ["auto-download"] } # Fix Linux/aarch64
```
This fails:
```
frida-gum = { git = "https://github.com/frida/frida-rust", rev = "9976bced744b0b4ad658f60825eee3083243cdbe", features = ["auto-download"] } # Update Frida to 16.0.2
```
This works again:
```
frida-gum = { git = "https://github.com/t4lz/frida-rust", branch = "linux-arm-frida16", features = ["auto-download"] }
```
Sorry for that.
=> Undo special linux-arm64 case.

frida-gum-sys/Cargo.toml, frida-sys/Cargo.toml
The current bindgen version (0.61) is buggy on many systems and clang versions leading to parsing errors related to anonymous structs and unions
=> Update bindgen to 0.63

frida-gum/src/lib.rs
Implement Copy, Clone, Hash, and Eq for NativePointers. Additionally, make NativePointer #[repr(transparent)], so it can be used in FFI just like the underlying `*mut c_void`.
=> Implement standard traits for NativePointer

frida-sys/src/lib.rs, frida/src/device.rs, frida/src/error.rs, frida/src/lib.rs, frida/src/process.rs, frida/src/variant.rs
I needed these things, so here they are. If you'd rather have self-contained PR's, happy to do that too,.
- Get a device's connection type (Local/Remote/USB).
- Get a device's system properties (e.g. os version, jailed/full access, interface list, UDID,...)
- Spawn a process on a device. Compared to the implementation in #101, this allows setting SpawnOptions.
- Kill a process on a device
Would be really cool to get these into a 0.14 release!
=> Add a couple of useful features to Device

Cargo.toml, examples/core/usb_device/Cargo.toml, examples/core/usb_device/src/main.rs, frida/src/device_manager.rs
Added a convenience method to get a device by its identifier. This is most useful if you have multiple USB or network devices attached and want to work with a specific one without having to enumerate all and find the one by id. 
Created a simple example that demonstrates the usage of the `get_device_by_type` and `get_device_by_id` methods.
=> Added get_device_by_id to the device_manager and example

frida-gum/src/memory_range.rs, frida-gum/src/range_details.rs
=> RangeDetails: don't return dangling pointers

frida-gum/src/instruction_writer/aarch64/writer.rs, frida-gum/src/instruction_writer/x86_64/writer.rs, frida-gum/src/lib.rs, frida-gum/src/memory_range.rs, frida-gum/src/module.rs, frida-gum/src/module_map.rs, frida-gum/src/range_details.rs, frida-gum/src/stalker/transformer.rs, frida/src/process.rs
It does not compile on nightly (`1.79.0-nightly (805813650 2024-03-31)` to be exact) due to the `#![deny(warnings)]` attribute and redundant imports becoming a warning. Thanks!
=> fix: compilation on nightly

frida/src/script.rs
This PR adds support for sending data to scripts which can be read using the `recv` function as detailed in the [frida docs](https://frida.re/docs/javascript-api/#communication-between-host-and-injected-process). Until RPC support is implemented (#105) this can be used to achieve a similar effect.
EDIT: RPC appears to be implemented using messages, see [the python implementation here](https://github.com/frida/frida-python/blob/e929477ecd4553bd6b73f76f8b395dbb29470aaf/frida/core.py#L498-L501) which could make this PR a requirement for an RPC implementation
=> feat (script): Add post method to Script

Cargo.toml, examples/core/console_log/src/main.rs, examples/core/list_exports/Cargo.toml, examples/core/list_exports/README.md, examples/core/list_exports/src/main.rs, frida-gum/src/interceptor.rs, frida-gum/src/stalker.rs, frida/Cargo.toml, frida/src/device.rs, frida/src/script.rs, frida/src/variant.rs
- Implemented the function `list_exports`. Included an example demonstrating how to use it.
- Updated the example `console_log` to align with the recent changes made to the `on_message` function.
- Adjusted types in `device.rs` and `variant.rs`: After adding serde to cargo, I encountered compilation issues with `frida_sys::FALSE`. I set the types to resolve these issues.
Please let me know if you have any notes. Once we get this approved I can move to finalize the RPC calls #105
=> list_exports func added and initial RPC code.

frida-gum/Cargo.toml, frida-gum/src/lib.rs, frida-gum/src/memory_range.rs, frida-gum/src/module.rs, frida-gum/src/module_map.rs, frida-gum/src/range_details.rs, frida-gum/src/stalker/transformer.rs
The use of an ad-hoc list of features to enable std is weird. It's better to centralize under one std feature that these features enable.
Fixes #154
=> frida-gum: add std feature

frida-gum/src/interceptor.rs
Without this, the acquired reference would leak.
=> frida-gum: unref Interceptor on Drop

frida-gum-sys/src/lib.rs, frida-gum/Cargo.toml, frida-gum/src/interceptor.rs, frida-gum/src/lib.rs, frida-gum/src/stalker.rs
This makes the Gum APIs sane with regards to calling obtain. If this is liked, I'll send another patch with a similar API for the frida crate. One note is that a spinlock was added to make it easier to implement the drop logic correctly.
=> frida-gum: use a singleton gum instance

Cargo.toml, examples/core/rpc_execute_function/Cargo.toml, examples/core/rpc_execute_function/README.md, examples/core/rpc_execute_function/src/main.rs, frida/src/error.rs, frida/src/script.rs
Added `script.exports` function. This fixes issue #105
=> Added script.exports. Fixes #105

frida/src/device_manager.rs
=> Fix issue when dropping DeviceManager

frida-sys/build.rs
When trying to compile some examples in macos I get errors like the next one:
```
Undefined symbols for architecture x86_64:
"_IOCreatePlugInInterfaceForService", referenced from:
_darwin_device_from_service in libfrida-core.a[471](libusb_os_darwin_usb.c.o)
_darwin_claim_interface in libfrida-core.a[471](libusb_os_darwin_usb.c.o)
"_IOIteratorNext", referenced from:
_darwin_init in libfrida-core.a[471](libusb_os_darwin_usb.c.o)
_darwin_devices_detached in libfrida-core.a[471](libusb_os_darwin_usb.c.o)
_darwin_devices_attached in libfrida-core.a[471](libusb_os_darwin_usb.c.o)
_darwin_clear_iterator in libfrida-core.a[471](libusb_os_darwin_usb.c.o)
_process_new_device in libfrida-core.a[471](libusb_os_darwin_usb.c.o)
_darwin_get_interface in libfrida-core.a[471](libusb_os_darwin_usb.c.o) …
```
=> Link with Security & IOKit frameworks in MacOS

examples/gum/debug_symbol/src/main.rs, examples/gum/hook_instruction/Cargo.toml, examples/gum/hook_instruction/src/lib.rs, examples/gum/hook_open/src/lib.rs, examples/gum/open/Cargo.toml, examples/gum/open/src/lib.rs, frida-gum/src/module.rs
In order to use the underlying C API global init should be called.
We hence force the creation of Gum to use Module::* functions.
We also use OnceLock instead of lazy_static! as discussed in the issue.
=> frida-gum: force frida-gum init to use Module (#98)

examples/core/inject_lib_blob/Cargo.toml, examples/core/inject_lib_blob/README.md, examples/core/inject_lib_blob/src/lib.rs, examples/core/inject_lib_blob/src/main.rs, examples/core/inject_lib_file/Cargo.toml, examples/core/inject_lib_file/README.md, examples/core/inject_lib_file/src/lib.rs, examples/core/inject_lib_file/src/main.rs
Added "inject_library" examples to help with documentation. Similar to the python version https://github.com/frida/frida-python/tree/main/examples/inject_library
=> Added inject_library examples

examples/core/console_log/Cargo.toml, examples/core/console_log/src/main.rs, examples/core/get_processes/Cargo.toml, examples/core/get_processes/src/main.rs, examples/core/hello/Cargo.toml, examples/core/hello/src/main.rs, examples/core/inject_lib_blob/Cargo.toml, examples/core/inject_lib_file/Cargo.toml, examples/core/list_exports/Cargo.toml, examples/core/list_exports/src/main.rs, examples/core/rpc_execute_function/Cargo.toml, examples/core/rpc_execute_function/src/main.rs, examples/core/usb_device/Cargo.toml
- Use of LazyLock instead of lazy_static
- Clean up unnecessary frida-sys & lazy_static crates
- Examples ran and tested
=> Core examples - use LazyLock & clean unnecessary crates

frida-gum/src/range_details.rs
This will be helpful when we do things like `Process.enumerateRanges(protection|specifier)` in Rust.
I am using the same string form as shown in the docs 
> protection given as a string of the form: `rwx`, where `rw-` means “must be at least readable and writable”.
=> PageProtection - Added Display implementation

examples/gum/script/build.rs, frida-gum-sys/build.rs
fix error when building `examples/gum/script`:
```
= note: Undefined symbols for architecture arm64:
"_res_9_dn_expand", referenced from:
_OUTLINED_FUNCTION_16 in libfrida_gum_sys-75fd3f9127f13c0d.rlib[1357](gthreadedresolver.c.o)
"_res_9_ndestroy", referenced from:
_do_lookup_records in libfrida_gum_sys-75fd3f9127f13c0d.rlib[1357](gthreadedresolver.c.o)
"_res_9_ninit", referenced from:
_do_lookup_records in libfrida_gum_sys-75fd3f9127f13c0d.rlib[1357](gthreadedresolver.c.o)
"_res_9_nquery", referenced from:
_do_lookup_records in libfrida_gum_sys-75fd3f9127f13c0d.rlib[1357](gthreadedresolver.c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
=> fix linkage for frida-gum script example for macos

examples/core/console_log/src/main.rs, examples/core/list_exports/src/main.rs, examples/core/rpc_execute_function/src/main.rs, frida-sys/src/lib.rs, frida/src/script.rs
Just a bit of plumbing that was missing.
Not sure whether the copy to a vector is strictly needed, it might be possible to get away without but I didn't want to risk it.
=> Implement support for accessing binary data sent alongside messages

frida-gum/src/process.rs
=> Added more function for Process

frida-gum-sys/build.rs, frida-sys/build.rs
The generated bindings are otherwise a single line which is hard for vscode to open. It's useful to poke around in the bindings when playing with the APIs. Prettyplease is fast. I don't see a downside to always enabling it, and it was already enabled as a default feature of bindgen.
=> frida-gum-sys,frida-sys: bindgen w/ prettyplease

frida-gum/src/instruction_writer/aarch64/writer.rs
Added #[cfg(not(feature = "std"))] attribute to conditionally import alloc::vec::Vec
ensures that Vec is only imported when the 'std' feature is not enabled
=> fix: "use of undeclared crate or module alloc" error on aarch64 when std feature is enabled

frida-gum/src/interceptor/invocation_listener.rs, frida-gum/src/script/scheduler.rs
Fix the build failure due to a hidden lifetime, similar to #211 (https://github.com/frida/frida-rust/pull/211/files#diff-11501e57faea644796e9f839a366d147145263e93fee2c139bfab1f3a8d7bfc2) 
```
error: hiding a lifetime that's elided elsewhere is confusing
--> frida-gum/src/interceptor/invocation_listener.rs:170:24
|
170 |     pub fn cpu_context(&self) -> CpuContext {
|                        ^^^^^     ---------- the same lifetime is hidden here
|                        |
|                        the lifetime is elided here
|
= help: the same lifetime is referred to in inconsistent ways, making the signature confusing
note: the lint level is defined here
--> frida-gum/src/lib.rs:49:9
|
49  | #![deny(warnings)]
|         ^^^^^^^^
= note: `#[deny(mismatched_lifetime_syntaxes)]` implied by …
```
=> Fix build failure on nightly

examples/core/console_log/src/main.rs, examples/core/list_exports/src/main.rs, examples/core/rpc_execute_function/src/main.rs, frida/src/script.rs
As discussed in #217, there’s no reason the message handler should only receive a reference to the message. Passing the value directly is more idiomatic in Rust and helps reduce memory allocation within the handler.
Although the Handler trait is public and changing the signature of its method constitutes a breaking change, the modification—both for us and for users—is straightforward. I believe it’s worth pursuing.
=> Change Handler trait to receive message by value
